service: shopify-orders-collector

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: ap-southeast-1
  timeout: 600
  environment:
    STAGE: ${opt:stage, 'dev'}

functions:
  consumer:
    handler: handler.consumer
    events:
      - sqs:
          batchSize: 1
          arn: arn:aws:sqs:ap-southeast-1:170274338432:shopify-orders-queue

  consumerHTTP:
    handler: handler.consumerHTTP
    events:
      - http:
          path: /
          method: POST
          cors: true

  airtableReplicator:
    handler: handler.airtableReplicator
    events:
      - sqs:
          batchSize: 1
          arn: arn:aws:sqs:ap-southeast-1:170274338432:shopify-orders-queue

  isgOrderSourceToASCMLogistics:
    handler: airtable.isgOrderSourceToASCMLogistics
    events:
      - http:
          path: /airtable/ascm-logistics
          method: GET
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
